name: CI/CD Pipeline Automação API PetStore

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configurar Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Compilar e Rodar Testes
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Upload Relatório de Testes
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: target/*.html