name: API Automation Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 📦 Configurar Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: 📦 Instalar Dependências
        run: mvn clean install -DskipTests

      - name: 🚀 Executar Testes
        run: mvn test -DsuiteXmlFile=suiteTest.xml

      - name: 📤 Upload do Relatório ExtentReports
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: test-output/extent-report.html
